# `DSML_WS_02` - Introduction to Python Library Management & `NumPy`

Please work on the following tasks **before** the second workshop session.

## 1. Programming a simple calculator in Python

Last week, you made yourself familiar with Python, getting to know about data structures like values, lists and dictionaries, explored for loops and if statements, and learned how to define functions. To put your knowledge of basic Python to the test, write a properly documented python function that can perform the taks of a simple calculator with the following behaviour:

1. The user shall pass the desired mathematical operation (plus, minus, divide, multiply) and two numbers

2. The result shall be calculated and printed

3. If the input for the mathematical operation is not covered by the list from above, print "Please correct your input"

**You should use the following elements:** 

- If/elif/else statement
- Functions
- Mathematical expressions

In [20]:
def simple_calc(first_num, ops, second_num):
    """
    Perform a mathematical operation between two numbers
    ...
    
    Arguments
    ---------
    first_num     : int/float
                    first number in calculation
                    
    ops           : str
                    mathematical operation; ops=["plus", "minus", "multiply", "divide"]
    
    second_num    : int/float
                    second number in calculation
    
    Returns
    -------
    result : str
            Operation and results of operation as string
    """
    #### your code below ####
    
    if ops == "plus":
        result = first_num + second_num
        output = f"{first_num} + {second_num} = {result}"
    elif ops == "minus":
        result = first_num - second_num
        output = f"{first_num} - {second_num} = {result}"        
    elif ops == "multiply":
        result = first_num * second_num
        output = f"{first_num} * {second_num} = {result}"
    elif ops == "divide":
        if second_num != 0:
            result = first_num / second_num
            output = f"{first_num} / {second_num} = {result}"
        else:
            output = "Error: Division by zero is not allowed."
    else:
        output = "Please correct your input"
    
    return output
        

In [21]:
# try out your calculator by calling the simple_calc function with different argument values
print(f"1.) {simple_calc(2, "plus", 2)}")
print("2.)", simple_calc(2, "minus", 2))
print("3.)", simple_calc(9, "multiply", 9))
print("4.)", simple_calc(27, "divide", -5))
print("5.)", simple_calc(2, "divide", 0))
print("6.)", simple_calc(2, "plu", 0))


1.) 2 + 2 = 4
2.) 2 - 2 = 0
3.) 9 * 9 = 81
4.) 27 / -5 = -5.4
5.) Error: Division by zero is not allowed.
6.) Please correct your input


## 2. Getting started with NumPy

This week, we will be exploring our first Python package, namely NumPy. Get prepared for the workshop by completing the below steps:

In order to use NumPy's capabilities, we first have to import it. Do this by running the following cell. We use the `as` keyword so we can use an abbreviation when calling NumPy methods.

In [22]:
import numpy as np

The core structure of NumPy is the N-dimensional array object. You can create arrays using `np.array([..,..,..])`. Do the following:
1. Create a list of 5 integers and assign it to a variable called `lst`.
2. Use `lst` to create a NumPy array, and assign this array to a variable called `my_first_array`.
3. Verify that the type of `my_first_array` is np.array.
4. Create a second array, consisting of the first 3 numbers from `my_first_array`, and assign it to a variable called `my_second_array` (tip: selecting a subset of elements from arrays works similarly to lists).
5. Create a third array, which contains each number from `my_second_array` multiplied by 3, and assign it to a variable called `my_third_array` (tip: thinking about list operations from last week will help you here once again).

In [45]:
# your code here
# 1.
lst = [1, 4, 2, 6, 19]

# 2.
my_first_array = np.array(lst)
my_first_array

# 3.
type(my_first_array)

# 4.
my_second_array = my_first_array[0:3]
my_second_array

# 5.
my_third_array = my_second_array * 3
my_third_array

array([ 3, 12,  6])

Finally, let's combine `my_second_array` and `my_third_array`. We can use the functions np.hstack((`first_array`,`second_array`)) or np.vstack((`first_array`,`second_array`)) for this. Combine `my_second_array` and `my_third_array` using both functions. How does the output differ? Can I also use both functions to combine `my_first_array`and `my_second_array`?

In [ ]:
# your code here
np.hstack((my_second_array, my_third_array))
# np.hstack combines 'next to each other' in one row

array([ 1,  4,  2,  3, 12,  6])

In [ ]:
np.vstack((my_second_array, my_third_array))
# np.vstack combines vertically, new row
# caution! arrays must be compatible

array([[ 1,  4,  2],
       [ 3, 12,  6]])

In [61]:
# that's why this doesn't work
np.vstack((my_first_array, my_second_array))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 3

In [62]:
np.hstack((my_first_array, my_second_array))

array([ 1,  4,  2,  6, 19,  1,  4,  2])